### ISSUE TITLE
消息以及联系人名称中的表情符号无法解析

### ISSUE THREAD

**Issue by mhyushantu** [fjqisba/WeChatStudy#1]
emoji是否可以正确转换通过接口返回？目前全部都是问号”？“

**Comment by fjqisba** [comment]
没遇到过呢。。。。其实，这软件写出来我根本就没用过

**Comment by mhyushantu** [comment]
很多用户喜欢昵称中带表情 如：A 居梵🔥 忆城🔥    读出来会变成 A 居梵？ 忆城？

**Comment by fjqisba** [comment]
收到，我有空研究研究吧

**Comment by fjqisba** [comment]
研究了一下，发现确实是我忽略了这个问题。
微信底层字符串都是unicode存储的，我是将其转成了ascii，再转成utf8。但是在转成ascii的时候特殊字符就没了。

**Comment by fjqisba** [comment]
问题已修复
