### ISSUE TITLE
微信登录后程序会崩溃

### ISSUE THREAD

**Issue by mhyushantu** [fjqisba/WeChatStudy#2]
win10操作系统，visual studio2022 编译运行，3.7.6.44版本微信和3.8.0.33版本在手机授权登录后，微信都会崩溃，经测试发现，

3.7.6.44版注释掉代码
` gHook_AccountSvrLogout.AddHook((LPVOID)(hWeChatWinDLL + 0x7240F0), AccountService_logout);`
 后可以正常进入微信；

3.8.0.33版则需要注释掉
`gHook_AccountSvrLogin.AddHook((LPVOID)(hWeChatWinDLL + 0xCC7BC0), AccountService_login);`
后可以正常进入微信。

![5F88A502-6F20-4CA6-980A-5EFC3BD4E7D6](https://user-images.githubusercontent.com/6027549/204190209-7775e725-0c03-4c40-ab88-ef684ab68db9.png)

**Comment by fjqisba** [comment]
已优化
