### ISSUE TITLE
win10 vs2022 protobuf-3.21.12编译一直出错

### ISSUE THREAD

**Issue by luochaolun** [fjqisba/WeChatStudy#3]
请问本项目中用的protobuf是哪个版本？

win10 vs2022 protobuf-3.21.12，编译了两天，一直出错！

微信3.7.6.44，请问是否需要特定版本的protobuf才行！

微信3.8.0.33，没找到下载链接。

如果你有微信3.7.6.44、微信3.8.0.33，能否共享下！
----------------------------------------------------------
把WeChatGUI\WeChatDLL\include\google\protobuf 下的头文件替换成最新版的protobuf头文件，终于可以编译成功了,在在C:\App\WeChat\[3.8.0.33]下，生成WeChatDLL.dll、WeChatDLL.exp、WeChatDLL.lib、WeChatDLL.pdb

但是不管是debug、还是release模式，WeChat.exe都加载不了WeChatDLL.dll(已将WeChatDLL.dll复制到微信安装目录，和WeChat.exe同一目录)？不应该在生成WeChatDLL.dll时，同时生成一个WeChat.exe么？

**Comment by fjqisba** [comment]
protobuf随便一个最近的版本，不要用工程里面的代码，编译出lib再引入即可。
微信的话暂时没有。
生成的DLL需要配合[WeChatClient](https://github.com/fjqisba/WeChatStudy/tree/main/WeChatClient)Python代码注入进行使用

**Comment by fjqisba** [comment]
已更新
