### ISSUE TITLE
请教3.8.1.26发送文件失败

### ISSUE THREAD

**Issue by nblog** [fjqisba/WeChatStudy#6]
3.8.0.33
https://github.com/fjqisba/WeChatStudy/blob/f2ab8c7147f0165cd656d5dd58c3eac527af0159/WeChatGUI/WeChatDLL/ApiServer.cpp#L71
是否测试过? 能发送吗?

[sendfile](https://github.com/nblog/my-fridajs-example/blob/dev/wechat.js#L133) 3.8.1.26 RVA:0xA10190
无法发送, 请问是我的问题吗?

**Comment by fjqisba** [comment]
测试过一次，需要你自行编译DLL，然后发送。
其它版本太麻烦，懒得看了

**Comment by nblog** [comment]
感谢, 那应该就是我这个版本用不了了, 我对比过3.8.0.33版本是同一个功能.
